---
output: 
  html_document:
    toc: true
    toc_depth: 6
    number_sections: no
    toc_float: yes
    code_folding: hide
    fig_crop: no
    date: '''r format(sys.time(), ''%d %B, %Y'')'''
editor_options: 
  markdown: 
    wrap: 72
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

# **Contact Information**

4028 South 1400 East

Salt Lake City, Utah, 84124

[ceruttinger\@gmail.com](mailto:ceruttinger@gmail.com){.email}

801-205-1514

# **Skills**

+---------------+---------------+---------------+--------------------+
| SQL, Python,  | RStudio,      | SPSS, SAS,    | Tableau            |
| Jupyter       | Github        | STATA         |                    |
| Notebook      |               |               |                    |
+---------------+---------------+---------------+--------------------+
| Data          | Amazon Cloud  | Graph         | Regression/        |
| Warehouse     | Architecture  | Database      | Classification     |
| Design        |               | Design        | Models             |
+---------------+---------------+---------------+--------------------+
| Grant Writing | Team Oriented | Problem       | Excellent          |
|               | Collaborator  | Solver        | Communicator       |
+---------------+---------------+---------------+--------------------+
| Health Policy | Research      | Systems       | Fluent Spanish     |
| Analysis      | Design        | Thinking      |                    |
+---------------+---------------+---------------+--------------------+

# **Work Experience**

## **Utah Health Workforce Information Center**

### Founding Director

*7.1.2022- present*

-   Engaged with a coalition of healthcare stakeholders in Utah over
    2020-21 to develop a strategic plan for improving health workforce
    data collection and policy guidance resulting in the passage of [HB
    176, The Utah Health Workforce
    Act](https://le.utah.gov/~2022/bills/static/HB0176.html) in the 2022
    legislative session.

    -   This legislation did three things:

        -   Created the Utah Health Workforce Information Center (HWIC)
            out of the workforce research team of the Utah Medical
            Education Council (UMEC).

        -   Integrated supplemental supply surveys of the health
            workforce with the license and renewal process in Utah and
            aligned access for the HWIC to various Utah Department of
            Health data sources to improve modeling and analytics.

        -   Created the Utah Health Workforce Advisory Committee to
            provide guidance on health policy resource allocation for
            legislators, administrators and policy makers.

-   Continuing duties of Director, Workforce Research from the UMEC.

-   Serving on the [Health Workforce Interest Group Advisory Committee
    for Academy
    Health.](https://academyhealth.org/professional-resources/interest-groups/health-workforce-interest-group/advisory-committee/page/health-workforce-interest-group-advisory-committee)

-   Serving on the expert work-group for the HRSA funded [Health
    Workforce Technical Assistance
    Center](https://www.healthworkforceta.org/about/expert-workgroup/)
    at the University of Albany.

-   Member of the Utah Hospital Association Workforce Committee, The
    Utah Nurse Action Coalition and the Utah Organization of Nurse
    Leaders Academic Leadership Committee.

-   [Serving in a consulting capacity with the University of Utah School
    of Nursing- on the HRSA ANEW grant- "Addressing Barriers to Primary
    Care Workforce Needs in Rural and Underserved Settings with
    Academic-Clinical Partnerships and Innovations in
    Technology".](https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=&ved=2ahUKEwiu6b6H-_H2AhUnLTQIHc4kDNcQFnoECAkQAQ&url=https%3A%2F%2Fgrants.hrsa.gov%2F2010%2Fweb2External%2FInterface%2FCommon%2FPublicWebLinkController.aspx%3FGrantNumber%3DT94HP32908%26WL_WEBLINK_ID%3D1&usg=AOvVaw3L5FVAtydxvfQEhMUDozcc)

-   Consulting the University of Utah School of Medicine- "American
    Indian Health Workforce Plan".

## **Utah Medical Education Council**

### Acting, Executive Director

*1.2022- 6.2022*

-   Oversaw merger and transition management of the UMEC to the HWIC
    within the Utah Department of Health and Human Services.

### Director, Workforce Research

*01.2018- 12.2021*

-   Supervise all research staff and interns.

-   Management of all research projects for the Council.

    -   Recipient of [IBM Healthcorps
        grant](https://ibmhealthcorpsblog.wordpress.com/) to model
        Primary Care workforce based on population health needs.

-   Provide high level expertise in research design, statistical
    analysis and emerging issues/trends.

-   Design, development and management of data cleaning processes, data
    warehousing, modeling and visualization.

-   Responsible for survey design, data collection, authoring/editing of
    research papers, project reports, policy and position papers,
    articles and technical reports.

-   Providing consultation, recommendations and support for executive
    level decision makers, educators administrators and researchers
    across the healthcare industry in Utah and nationally regarding
    medical workforce policy issues.

-   Designed and maintained Amazon Cloud environment for research
    purposes

    -   Managed creation of data warehouse environment for storing
        supply data sets for analysis.

    -   Set up an
        [RShiny](https://www.rstudio.com/products/shiny/shiny-server/)
        server in AWS cloud to publish interactive data visualizations.

    -   Set up a [NEO4J graph database](https://neo4j.com) in AWS cloud
        with web browser interface on a utah.gov domain to query and
        analyze state [APCD](https://www.apcdcouncil.org/) data.

### Senior Institutional Research Analyst

*01.2016 -2018*

-   Director of Utah's Nursing Workforce Information Center.

    -   Responsible for mentoring and direction of the work of research
        analyst team.

        -   Gather survey data, analyze, present and advise on nurse
            education, supply and demand.

        -   Created methodology, data linkage and authored the first
            [Utah Nursing Employment Demand
            Study](https://drive.google.com/file/d/1jGr4R_3pm-E0YRr5kV19EHaO6N5DwXxE/view?usp=sharing)
            as required in
            [statute](https://le.utah.gov/~2018/bills/static/SB0147.html)
            by the State legislature beginning in 2020.

### Research Analyst

*01.2010 -- 12.2015*

-   Consulting, research, surveying, analysis and policy recommendation
    development for all categories of the Utah healthcare workforce (ie:
    physicians, dentists, PAs, APRNs, pharmacists)

    -   Increased frequency of cyclical workforce reporting by 20%
        <br></br>

-   Secure management of all data received by the office from state
    agencies and health professional training programs.

    -   Wrote VBA code to clean and organize data for analysis.

-   Maintain the state of Utah's Physician Resident Rotation Database;
    allowing for resident training hospitals to assure maximum
    reimbursement from Medicare for Graduate Medical Education training.

    -   Wrote VBA code to format and combine multiple large spreadsheets
        into a standard format.

## **Valley Mental Health/Hopeful Beginnings**

### Respite Care Provider

*06.2006 -- 06.2015*

-   Provided weekly behavior modeling, opportunities for social
    interaction and activities for youth diagnosed with behavioral
    disorders receiving services through medicaid service providers
    Valley Mental Health and Hopeful Beginnings in Utah.

## **State of Utah- Department of Workforce Services**

### Administrative Hearing Specialist

*03.2008 -- 12.2009*

-   Acted as presiding officer in the review and representation of the
    State in administrative action against individuals who had incurred
    a public assistance overpayment.

    -   Created macros to increase speed and accuracy of processing
        administrative actions <br></br>

-   Reviewed the work of an Overpayment Calculation Analyst for
    accuracy, correct administrative legal classification and proper
    supporting evidence to order an overpayment of welfare benefits.

    -   Pulled welfare benefit data using an Oracle SQL graphic user
        interface. <br></br>

-   Responsible for explanation and presentation of complex welfare
    policies within the setting of an administrative hearing in front of
    an Administrative Law Judge to overpaid individuals and legal
    counsel.

### Eligibility Specialist

*06.2005 -- 02.2008*

-   Interpreted federal and state welfare policies including TANF, Food
    Stamps and Child Care to approve application for benefits.

-   Medicaid specialist embedded at [Community Health Centers-
    Utah](https://www.chc-ut.org/).

## **The Road Home**

### Grants Coordinator

*10.2003 -- 01.2005*

-   Researched, wrote, submitted and reported on over 150 established
    grants per year from foundations, corporations and government.

-   Tracked the receipt and recognition of grant and donation monies
    through donor database software.

-   Assisted Development staff with the planning of all yearly
    fundraisers, direct mailings, volunteer coordination, updating
    agency website and education of the public through tours and
    speaking engagements.

### Housing Case Manager

*10.2002 --10.2003*

-   Provided Case management services to between 20 and 30 clients at
    any time Assisted clients with referrals to any community assistance
    programs available.

-   Coordination with community agencies to assure clients receipt of
    services.

## **Americorps**

### Wasatch Homeless Health Care- Care Coordinator *2002*

-   Interviewed patients to assess eligibility for private clinic and
    public health care programs.

-   Developed and implemented procedures and training for the care
    coordination position.

-   Assisted clients in arranging to receive medical services at no cost
    through local medical providers who were willing to voluntarily
    donate their professional services.

# **Education**

## **Master of Business Administration** *University of Utah, 2017*

-   Certificate in Information Systems

## **Master of Public Administration** *University of Utah, 2007*

-   Emphasis in Program Evaluation and Policy Analysis

## **Utah Dispute Resolution** *Utah State Bar, 2008*

-   40 hours of Basic Mediation Training

## **BA, Political Science/ BA, Spanish** *University of Utah, 1998-2002*

-   Certificate in International Relations

-   Hinkley Institute of Politics, Summer Internship

    -   Chasqui Humanitarian- Cuzco Peru, 2000

        -   Assisted with development and implementation of humanitarian
            aid projects such as health and hygiene clinics,
            construction of modern restroom facilities, and micro-credit
            loan programs for small businesses. 

        -   Supervision and management of volunteer work groups from the
            U.S. who came to Peru to assist in aid projects the
            organization had developed.

# **Volunteer Experience**

## [National Forum of State Nursing Workforce Centers](http://nursingworkforcecenters.org/){target="_blank" rel="noopener noreferrer"}

### Board Member *2018-2020*/ Board President *2019*

-   Sharing best practices in policy, planning and advocacy of
    healthcare workforce issues across member states. Focused on
    supporting nursing in the context of improving the nursing role in
    the inter-professional care team.

-   Working on data driven decision making tools to support better
    resource allocation for healthcare policy makers at the state and
    national level.

## [U.S. Department of Health and Human Services Health Resources and Services Division (HRSA)](https://www.hrsa.gov){target="_blank" rel="noopener noreferrer"}

### Grant Reviewer *01.2011- present*

-   Objectively evaluate and score grant applications against published
    evaluation criteria in order to advise the federal government on
    selecting the best programs for funding from a competitive group of
    applicants.

## [**Salt Lake City Planning Commission**](https://www.slc.gov/boards/boards-commissions/planning-commission/)

### Planning Commissioner *11.2011- 2019*

-   Adopt and act on any changes to the City's master plans, small area
    plans, special studies, zoning ordinances, and zoning district maps,
    approving planned unit developments, conditional uses and certain
    subdivisions.

    -   Commission Chair for the 2015 year.

## [**Community Action Program**](https://www.utahca.org/)

### Landlord/Tenant Mediator *2009*

-   Mediated between landlords and tenants in pre and post eviction
    filing processes in issues of repairs and maintenance, late rent,
    lease violations, utilities, privacy issues etc

# **Publications**

## **Peer Reviewed Journal Articles**

1.  [Bounsanga et al, Using machine learning to identify factors
    associated with practice location of the healthcare workforce, Rural
    and Remote Health,
    2022](https://www.rrh.org.au/journal/article/7050){target="_blank"
    rel="noopener noreferrer"}

2.  [Smiley et al, The 2020 National Nursing Workforce Survey, Journal
    of Nursing Regulation,
    2020](https://www.journalofnursingregulation.com/article/S2155-8256(21)00027-2/fulltext){target="_blank"
    rel="noopener noreferrer"}

    -   [Post publication dashboard I designed and coded in R
        Shiny](https://clarkruttinger.shinyapps.io/draftboard/){target="_blank"
        rel="noopener noreferrer"}

## **Published Analysis**

1.  [Utah Medical Education Council (2021). Utah's Mental Health
    Workforce, 2021. Salt Lake City, UT. Utah Medical Education Council
    (2020).](https://umec.utah.gov/publications/mental-health/)

2.  [Utah's Physician Workforce, 2020. Salt Lake City, UT. Utah Medical
    Education Council
    (2020).](https://umec.utah.gov/wp-content/uploads/2020-Physician-Workforce-Report-final.pdf)

3.  [Utah Supply of Registered Nurses and Licensed Practical
    Nurses, 2020. Salt Lake City, UT. Utah Medical Education Council
    (2020).](https://umec-nursing.utah.gov/wp-content/uploads/UtahRN-LPNSupply2020-Final.pdf)

4.  [Utah Nursing Demand 2020. Salt Lake City, UT. Utah Medical
    Education Council
    (2017).](https://umec-nursing.utah.gov/wp-content/uploads/UtahRNEmploymentDemand2020.pdf)

5.  [Utah's Advanced Practice Registered Nurse Workforce, 2017: A Study
    of the Supply and Distribution of APRNs in Utah. Salt Lake City, UT.
    Utah Medical Education Council
    (2016).](https://umec-nursing.utah.gov/wp-content/uploads/APRN_2017_FINAL.pdf)

6.  [Utah's Physician Workforce, 2016: A Study of the Supply and
    Distribution of Physicians in Utah. Salt Lake City, UT. Utah Medical
    Education Council
    (2016).](https://umec-nursing.utah.gov/wp-content/uploads/APRN_2017_FINAL.pdf)

7.  [Supply of Nurses in Utah: The 2016 Survey Utah's Registered Nurses.
    Salt Lake City, UT. Utah Medical Education Council
    (2013).](https://umec-nursing.utah.gov/wp-content/uploads/RN-report-final-updated5-9-2016.pdf)

8.  [Utah's Advanced Practice Registered Nurse Workforce, 2013: A Study
    of the Supply and Distribution of APRNs in Utah. Salt Lake City,
    UT.](https://umec-nursing.utah.gov/wp-content/uploads/2013APRNReport.pdf)

# **References**

## Available Upon Request

<!-- ## [Michael K. Magill,MD](https://www.theabfm.org/about/board/michael-k-magill-md) -->

<!-- Professor Emeritus, University of Utah -->

<!-- Department of Family and Preventive Medicine -->

<!-- Chair, American Board of Family Medicine -->

<!-- [michael.magill\@hsc.utah.edu](mailto:michael.magill@hsc.utah.edu){.email} -->

<!-- 375 Chipeta Way, Suite A -->

<!-- Salt Lake City, UT 84108 -->

<!-- 801-554-3653 -->

<!-- ## [Paul B. Jackson](https://www.utahhospitals.org/contact) -->

<!-- Workforce Consultant -->

<!-- Utah Hospital Association -->

<!-- 2180 South 1300 East, Suite 440 -->

<!-- Salt Lake City, Utah 84106 -->

<!-- [jacksonjenna\@msn.com](mailto:jacksonjenna@msn.com){.email} -->

<!-- 801-520-2378 -->

<!-- ## [Jana Bitton, MPA](https://www.linkedin.com/in/janabitton/) -->

<!-- Executive Director, Oregon Center for Nursing -->

<!-- President, National Forum of State Nursing Workforce Centers -->

<!-- 5000 N. Willamette Blvd. MS 192 -->

<!-- Portland, OR 97203 -->

<!-- 360-609-0221 -->

<!-- [jana.bitton\@oregoncenterfornursing.org](mailto:jana.bitton@oregoncenterfornursing.org){.email} -->
